name: 'Deploy ASP.NET Core app to Azure Web App'

on:
  push:
    branches:
      - "main"

env:
  DOTNET_VERSION: '3.1.404'


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Run dotnet build and publish
      - name: dotnet build and publish
        working-directory: 'app'
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o './published-app'

      # Publish artifact
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: published-app
          path: './app/published-app'

  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: build-and-publish
    steps:

      # Download published artifact
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: published-app
          path: './published-app'

      # Deploy to web app
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-cloudlumberjack-dev
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './published-app'

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [build-and-publish, deploy-dev]
    steps:

      # Download published artifact
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: published-app
          path: './published-app'

      # Deploy to web app
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-cloudlumberjack-prod
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './published-app'
